### ISSUE TITLE
What does this mod do?

### ISSUE THREAD

**Issue by f1amy** [whatdahopper/FixEverything#1]
Title basically

**Comment by ArcaneEntity** [comment]
bro give us a list of changes/features, no one wants to be adding more bloatware to their computers

**Comment by whatdahopper** [comment]
If you actually read the release notes you'd know what it fixes, I didn't list the fixes/features on the readme because they'll change with every update to this mod.

I make mods for fun. If you don't like the way I operate then don't use my mods, they're free anyways. I don't get paid nearly as enough to put the effort to make these things insanely polished so that even the dumbest of the dumb know what they're getting into, if you have a problem with the way I operate consider donating to my Patreon and maybe I'll put a little more effort into making my free mods dumb enough and obvious to everyone.
